/**
 * Investment Lab — content model + seed.
 *
 * Everything here is CMS-editable via admin → Investment Lab. Nothing in the
 * Lab UI reads a hardcoded value.
 *
 * The portfolio is explicitly HYPOTHETICAL: an educational record of process,
 * not a performance claim. The disclosure is part of the data model so it can
 * never be silently dropped from the page.
 */

export const ASSET_CLASSES = [
  'Indian Stocks', 'US Stocks', 'ETFs', 'Mutual Funds', 'Index Funds',
  'Gold ETF', 'REITs', 'INVITs', 'Bonds', 'Government Securities',
  'Fixed Deposits', 'Cash', 'Crypto', 'Alternative Investments',
]

export const EXCHANGES = ['NSE', 'BSE', 'NYSE', 'NASDAQ', 'AMEX', 'LSE', 'SGX', 'N/A']

export const HOLDING_STATUS = ['Holding', 'Exited', 'Watchlist', 'Closed']

export const BENCHMARKS = [
  { id: 'nifty50', label: 'NIFTY 50', symbol: '^NSEI' },
  { id: 'nifty500', label: 'NIFTY 500', symbol: '^CRSLDX' },
  { id: 'sensex', label: 'SENSEX', symbol: '^BSESN' },
  { id: 'nasdaq', label: 'NASDAQ', symbol: '^IXIC' },
  { id: 'sp500', label: 'S&P 500', symbol: '^GSPC' },
  { id: 'custom', label: 'Custom', symbol: '' },
]

export const CURRENCIES = ['INR', 'USD', 'EUR', 'GBP', 'SGD']

export const LAB_DISCLOSURE =
  'This portfolio is hypothetical and created solely for educational, research and portfolio construction purposes. It does not represent actual investments or constitute investment advice.'

export const LAB_SETTINGS = {
  enabled: true,
  portfolioName: 'Hypothetical India Portfolio',
  initialCapital: 10000000, // ₹1,00,00,000
  startDate: '2023-04-01',
  baseCurrency: 'INR',
  // FX: units of base currency per 1 unit of the quoted currency.
  // Admin-editable; a missing rate makes the position unconvertible and is
  // surfaced as a warning rather than silently summed at 1:1.
  fxRates: { INR: 1, USD: 83.5, EUR: 90.2, GBP: 106.4, SGD: 62.1 },
  benchmark: 'nifty50',
  benchmarkCustomSymbol: '',
  riskFreeRate: 0.07, // 10Y GSec — used for Sharpe / Treynor / Jensen
  description:
    'A hypothetical ₹1 crore book run as a concentrated, research-led portfolio. Every position exists to answer one question: is this the best available use of the next rupee of capital?',
  philosophy:
    'Own quality businesses at defensible prices; size by conviction and downside, not by excitement; let compounding run and never interrupt it unnecessarily. The record below is kept in full — including the mistakes — because a track record without the errors is marketing, not research.',
  horizon: '5–10 years',
  riskProfile: 'Moderate — concentrated, long-only, no leverage',
  disclosure: LAB_DISCLOSURE,
}

/** Blank instrument — the shape the admin form writes. */
export const EMPTY_INSTRUMENT = {
  id: '',
  name: '',
  ticker: '',
  exchange: 'NSE',
  isin: '',
  sector: '',
  industry: '',
  country: 'India',
  assetClass: 'Indian Stocks',
  entryDate: '',
  entryPrice: 0,
  currentPrice: null,
  exitPrice: null,
  exitDate: '',
  quantity: 0,
  targetAllocation: 0,
  status: 'Holding',
  averageCost: 0,
  targetPrice: null,
  stopLoss: null,
  horizon: '',
  currency: 'INR',
  notes: '',
  tags: [],
  logoUrl: '',
  coverImageUrl: '',
  enabled: true,
  order: 0,
  memo: {
    thesis: '', whyBought: '', valuation: '', catalysts: '', risks: '',
    moat: '', management: '', industryOutlook: '', financialSnapshot: '',
    keyRatios: '', exitStrategy: '', monitoringChecklist: '', lessons: '',
    attachments: [],
  },
}

export const LAB_HOLDINGS = [
  {
    id: 'h-hdfcbank',
    name: 'HDFC Bank',
    ticker: 'HDFCBANK.NS',
    exchange: 'NSE',
    isin: 'INE040A01034',
    sector: 'Financials',
    industry: 'Private Sector Bank',
    country: 'India',
    assetClass: 'Indian Stocks',
    entryDate: '2023-04-12',
    entryPrice: 1620,
    currentPrice: 1735,
    quantity: 620,
    targetAllocation: 12,
    status: 'Holding',
    averageCost: 1620,
    targetPrice: 2100,
    stopLoss: null,
    horizon: '5+ years',
    currency: 'INR',
    notes: 'Core compounder. Post-merger deposit repricing is the swing factor.',
    tags: ['Core', 'Compounder', 'Financials'],
    logoUrl: '', coverImageUrl: '', enabled: true, order: 1,
    memo: {
      thesis: 'Best-in-class liability franchise in a structurally under-penetrated credit market. The merger creates a temporary optical drag on NIM and CASA that the market is extrapolating as permanent — that gap is the opportunity.',
      whyBought: 'Bought when the post-merger de-rating pushed P/ABV to ~2.4x, roughly a standard deviation below its own 10-year mean, despite no impairment of the underlying deposit franchise.',
      valuation: 'P/ABV 2.4x vs 10Y mean ~3.4x. Reverse-DCF implies ~11% terminal loan growth — below the last decade actual. Base case fair value ₹2,050–2,150.',
      catalysts: 'CASA normalisation; branch productivity from the merged base; retail mix shift back toward unsecured; eventual index-weight normalisation.',
      risks: 'Deposit repricing takes longer than modelled; unsecured credit cost cycle; key-man risk at the top; regulatory tightening on LCR.',
      moat: 'Distribution + deposit cost. Hard to replicate in under a decade.',
      management: 'Deep bench; conservative provisioning history through two credit cycles.',
      industryOutlook: 'Credit growth tracking ~1.2x nominal GDP. Consolidation favours the top 4 private banks.',
      financialSnapshot: 'NIM ~3.4% | ROA ~1.8% | GNPA ~1.3% | CASA ~38%',
      keyRatios: 'P/ABV 2.4x · P/E 18x · ROE 15.7%',
      exitStrategy: 'Trim above 3.2x P/ABV or if CASA stays below 35% for four consecutive quarters without a credible path back.',
      monitoringChecklist: 'Quarterly: CASA ratio, NIM trajectory, slippages, LCR, branch adds.',
      lessons: 'Sized in too early — the de-rating ran a further 8% after entry. Conviction was right; the entry schedule was not. Should have laddered across three tranches.',
      attachments: [],
    },
  },
  {
    id: 'h-infy',
    name: 'Infosys',
    ticker: 'INFY.NS',
    exchange: 'NSE',
    isin: 'INE009A01021',
    sector: 'Information Technology',
    industry: 'IT Services',
    country: 'India',
    assetClass: 'Indian Stocks',
    entryDate: '2023-06-20',
    entryPrice: 1290,
    currentPrice: 1512,
    quantity: 500,
    targetAllocation: 9,
    status: 'Holding',
    averageCost: 1290,
    targetPrice: 1750,
    horizon: '3–5 years',
    currency: 'INR',
    notes: 'Cash-return story; AI is the key debate.',
    tags: ['Quality', 'Cash Return'],
    logoUrl: '', coverImageUrl: '', enabled: true, order: 2,
    memo: {
      thesis: 'Mid-teens FCF yield on a business with negative working capital and a 85%+ payout commitment. The AI-disruption narrative is priced as terminal; the evidence so far reads as mix shift, not revenue destruction.',
      whyBought: 'Entered at ~19x forward vs a 10Y median of ~24x, when discretionary-spend fear was at peak and the buyback was already announced.',
      valuation: '19x forward earnings; EV/EBITDA 13.5x; FCF yield ~5.2%. DCF at 11.5% WACC, 4% terminal → ₹1,700–1,800.',
      catalysts: 'Discretionary spend recovery; large-deal TCV; buyback execution; AI-led deal wins converting to revenue.',
      risks: 'AI compresses pricing faster than volume expands; US BFSI slowdown; wage inflation; visa policy.',
      moat: 'Switching costs on embedded systems; delivery scale.',
      management: 'Capital allocation is disciplined — consistent buybacks over empire-building.',
      industryOutlook: 'Structural, but pricing model in transition from effort-based to outcome-based.',
      financialSnapshot: 'Revenue growth ~4% cc | EBIT margin ~21% | FCF conversion ~95%',
      keyRatios: 'P/E 19x · EV/EBITDA 13.5x · ROE 31%',
      exitStrategy: 'Exit if two consecutive quarters show pricing decline attributable to AI substitution rather than mix.',
      monitoringChecklist: 'Quarterly: TCV, headcount vs revenue, pricing per FTE, attrition.',
      lessons: '',
      attachments: [],
    },
  },
  {
    id: 'h-niftybees',
    name: 'Nippon India ETF Nifty 50 BeES',
    ticker: 'NIFTYBEES.NS',
    exchange: 'NSE',
    isin: 'INF204KB14I2',
    sector: 'Diversified',
    industry: 'Index ETF',
    country: 'India',
    assetClass: 'ETFs',
    entryDate: '2023-04-01',
    entryPrice: 198,
    currentPrice: 262,
    quantity: 8000,
    targetAllocation: 18,
    status: 'Holding',
    averageCost: 198,
    horizon: '10+ years',
    currency: 'INR',
    notes: 'Core beta sleeve. Keeps the book honest about alpha.',
    tags: ['Core', 'Passive'],
    logoUrl: '', coverImageUrl: '', enabled: true, order: 3,
    memo: {
      thesis: 'The passive sleeve is deliberate: it anchors the book to market beta and makes stock-selection alpha measurable rather than assumed.',
      whyBought: 'Structural allocation from day one, not a tactical call.',
      valuation: 'N/A — index vehicle.',
      catalysts: 'N/A',
      risks: 'Index concentration in financials; tracking error; no downside protection.',
      moat: 'N/A', management: 'N/A',
      industryOutlook: 'N/A',
      financialSnapshot: 'TER 0.04% | Tracking error ~0.08%',
      keyRatios: 'N/A',
      exitStrategy: 'Permanent sleeve; rebalance to target on ±5% drift.',
      monitoringChecklist: 'Annual: TER, tracking error, AUM.',
      lessons: '',
      attachments: [],
    },
  },
  {
    id: 'h-goldbees',
    name: 'Nippon India ETF Gold BeES',
    ticker: 'GOLDBEES.NS',
    exchange: 'NSE',
    isin: 'INF204KB17I1',
    sector: 'Commodities',
    industry: 'Gold ETF',
    country: 'India',
    assetClass: 'Gold ETF',
    entryDate: '2023-05-15',
    entryPrice: 52,
    currentPrice: 71,
    quantity: 18000,
    targetAllocation: 10,
    status: 'Holding',
    averageCost: 52,
    horizon: '10+ years',
    currency: 'INR',
    notes: 'Correlation ballast, not a return engine.',
    tags: ['Hedge', 'Diversifier'],
    logoUrl: '', coverImageUrl: '', enabled: true, order: 4,
    memo: {
      thesis: 'Held for its correlation profile, not its expected return. Gold earns its place by what it does to portfolio variance in equity drawdowns.',
      whyBought: 'Rules-based 10% sleeve; rebalanced annually.',
      valuation: 'N/A — no cash flows to discount.',
      catalysts: 'Real-rate compression; central bank buying; INR depreciation.',
      risks: 'Zero yield; opportunity cost in equity bull markets; real-rate spikes.',
      moat: 'N/A', management: 'N/A',
      industryOutlook: 'N/A',
      financialSnapshot: 'TER 0.82%',
      keyRatios: 'N/A',
      exitStrategy: 'Rebalance to 10% on ±3% drift. No tactical trading.',
      monitoringChecklist: 'Annual: weight drift, real rates.',
      lessons: 'Correct call for the wrong reason — bought as an inflation hedge, and it worked via real rates and central-bank demand. Being right by accident is not a repeatable process.',
      attachments: [],
    },
  },
  {
    id: 'h-embassy',
    name: 'Embassy Office Parks REIT',
    ticker: 'EMBASSY.NS',
    exchange: 'NSE',
    isin: 'INE041025011',
    sector: 'Real Estate',
    industry: 'Office REIT',
    country: 'India',
    assetClass: 'REITs',
    entryDate: '2023-09-05',
    entryPrice: 312,
    currentPrice: 358,
    quantity: 2200,
    targetAllocation: 7,
    status: 'Holding',
    averageCost: 312,
    targetPrice: 420,
    horizon: '5+ years',
    currency: 'INR',
    notes: 'Yield sleeve. Occupancy is the whole thesis.',
    tags: ['Income', 'Real Assets'],
    logoUrl: '', coverImageUrl: '', enabled: true, order: 5,
    memo: {
      thesis: 'Grade-A office assets at a discount to NAV, with a distribution yield above the 10Y GSec. The market priced permanent WFH impairment; leasing data suggests otherwise for Grade-A in India.',
      whyBought: 'Entered at ~18% discount to NAV with distribution yield ~6.8%.',
      valuation: 'Discount to NAV ~18%; cap rate ~8.1%; distribution yield 6.8%.',
      catalysts: 'Occupancy recovery above 88%; GCC leasing demand; rate cuts.',
      risks: 'WFH structural drag; tenant concentration in tech; rate sensitivity; SEZ regulation.',
      moat: 'Irreplaceable Grade-A locations; scale.',
      management: 'Institutional sponsor; disciplined leverage.',
      industryOutlook: 'GCC expansion is the demand engine for Indian Grade-A office.',
      financialSnapshot: 'Occupancy ~85% | WALE ~7 yrs | LTV ~28%',
      keyRatios: 'P/NAV 0.82x · Distribution yield 6.8%',
      exitStrategy: 'Exit if occupancy sustains below 80% or LTV breaches 40%.',
      monitoringChecklist: 'Quarterly: occupancy, re-leasing spreads, LTV, distribution.',
      lessons: '',
      attachments: [],
    },
  },
  {
    id: 'h-msft',
    name: 'Microsoft',
    ticker: 'MSFT',
    exchange: 'NASDAQ',
    isin: 'US5949181045',
    sector: 'Information Technology',
    industry: 'Software',
    country: 'United States',
    assetClass: 'US Stocks',
    entryDate: '2023-07-18',
    entryPrice: 345,
    currentPrice: 421,
    quantity: 90,
    targetAllocation: 8,
    status: 'Holding',
    averageCost: 345,
    targetPrice: 480,
    horizon: '5+ years',
    currency: 'USD',
    notes: 'Held in USD — FX is part of the return.',
    tags: ['Quality', 'Global'],
    logoUrl: '', coverImageUrl: '', enabled: true, order: 6,
    memo: {
      thesis: 'The clearest monetisation path in enterprise AI, attached to an already-installed base with negligible incremental distribution cost. Azure is the toll road.',
      whyBought: 'Entered at ~30x forward — a premium, justified by the Copilot attach rate and Azure backlog.',
      valuation: '30x forward; EV/EBITDA 21x. Rich, and knowingly so.',
      catalysts: 'Copilot seat conversion; Azure AI revenue disclosure; operating leverage.',
      risks: 'Capex intensity compresses ROIC; AI monetisation slower than priced; antitrust; USD/INR reversal.',
      moat: 'Enterprise lock-in; developer ecosystem.',
      management: 'Best-in-class capital allocation under Nadella.',
      industryOutlook: 'Enterprise AI spend is early; the infrastructure bill is not.',
      financialSnapshot: 'Azure growth ~30% | Op margin ~44% | FCF ~$70B',
      keyRatios: 'P/E 30x · EV/EBITDA 21x · ROE 38%',
      exitStrategy: 'Trim above 38x forward, or if Azure growth decelerates below 20% for two quarters.',
      monitoringChecklist: 'Quarterly: Azure growth, capex/revenue, Copilot disclosure, FCF margin.',
      lessons: '',
      attachments: [],
    },
  },
  {
    id: 'h-gsec',
    name: 'GOI 7.26% 2033',
    ticker: 'IN0020230028',
    exchange: 'N/A',
    isin: 'IN0020230028',
    sector: 'Sovereign',
    industry: 'Government Security',
    country: 'India',
    assetClass: 'Government Securities',
    entryDate: '2023-08-10',
    entryPrice: 99.2,
    currentPrice: 101.4,
    quantity: 12000,
    targetAllocation: 12,
    status: 'Holding',
    averageCost: 99.2,
    horizon: '10 years',
    currency: 'INR',
    notes: 'Duration sleeve — the risk-free anchor.',
    tags: ['Sovereign', 'Duration'],
    logoUrl: '', coverImageUrl: '', enabled: true, order: 7,
    memo: {
      thesis: 'Locks a 7.26% sovereign coupon for a decade and supplies genuine negative correlation in an equity drawdown. This is the anchor the equity risk is measured against.',
      whyBought: 'Bought near the top of the rate cycle to lock duration before cuts.',
      valuation: 'YTM ~7.1% | Modified duration ~6.8',
      catalysts: 'RBI easing; index inclusion flows.',
      risks: 'Fiscal slippage; inflation resurgence; duration mark-to-market.',
      moat: 'N/A', management: 'N/A',
      industryOutlook: 'N/A',
      financialSnapshot: 'Coupon 7.26% | Maturity 2033',
      keyRatios: 'YTM 7.1% · Duration 6.8',
      exitStrategy: 'Hold to maturity unless real yields turn persistently negative.',
      monitoringChecklist: 'Quarterly: yield curve, fiscal deficit, CPI trajectory.',
      lessons: '',
      attachments: [],
    },
  },
  {
    id: 'h-paytm',
    name: 'One97 Communications (Paytm)',
    ticker: 'PAYTM.NS',
    exchange: 'NSE',
    isin: 'INE982J01020',
    sector: 'Financials',
    industry: 'Fintech',
    country: 'India',
    assetClass: 'Indian Stocks',
    entryDate: '2023-10-02',
    entryPrice: 890,
    exitPrice: 640,
    exitDate: '2024-02-05',
    currentPrice: 640,
    quantity: 300,
    targetAllocation: 0,
    status: 'Exited',
    averageCost: 890,
    horizon: '3 years',
    currency: 'INR',
    notes: 'Exited at a loss on regulatory action. Kept visible on purpose.',
    tags: ['Mistake', 'Exited'],
    logoUrl: '', coverImageUrl: '', enabled: true, order: 8,
    memo: {
      thesis: 'Original thesis: payments scale converting to lending take-rate, with a path to contribution-margin breakeven.',
      whyBought: 'Optionality on distribution reach at a depressed price after the IPO de-rating.',
      valuation: 'Was valued on EV/contribution profit — a metric that flatters pre-profit businesses.',
      catalysts: 'Never materialised.',
      risks: 'Underweighted the single risk that mattered: regulatory dependence on a bank licence I did not control.',
      moat: 'Thinner than the merchant count implied.',
      management: 'Governance concerns were visible in the DRHP and I discounted them.',
      industryOutlook: 'Payments is a feature; lending is the business — and lending requires a licence.',
      financialSnapshot: 'Exited at -28.1% (-₹75,000)',
      keyRatios: 'N/A',
      exitStrategy: 'Executed — sold on the RBI action, no averaging down.',
      monitoringChecklist: 'N/A — position closed.',
      lessons: 'The real error was pre-mortem, not exit. I sized a position whose core dependency was a regulator\'s discretion, and I had no way to monitor it. Rule added: if the single largest risk is binary and unobservable, the position size must reflect that it can go to zero — or I do not take it. Exiting on the news rather than averaging down was the one thing done right.',
      attachments: [],
    },
  },
  {
    id: 'h-titan',
    name: 'Titan Company',
    ticker: 'TITAN.NS',
    exchange: 'NSE',
    isin: 'INE280A01028',
    sector: 'Consumer Discretionary',
    industry: 'Jewellery & Watches',
    country: 'India',
    assetClass: 'Indian Stocks',
    entryDate: '',
    entryPrice: 0,
    currentPrice: 3290,
    quantity: 0,
    targetAllocation: 0,
    status: 'Watchlist',
    averageCost: 0,
    targetPrice: 2900,
    horizon: '5+ years',
    currency: 'INR',
    notes: 'Great business, wrong price. Waiting.',
    tags: ['Watchlist', 'Quality'],
    logoUrl: '', coverImageUrl: '', enabled: true, order: 9,
    memo: {
      thesis: 'Formalisation of Indian jewellery retail is a decade-long share-gain story with a genuine brand moat.',
      whyBought: 'Not bought. Business quality is not in question; the entry price is.',
      valuation: '68x forward vs 10Y median ~55x. Needs ~20% earnings CAGR for a decade to justify — possible, not probable.',
      catalysts: 'Gold price stability; studded mix; a valuation reset.',
      risks: 'Paying up for quality is still paying up. Gold volatility; competitive intensity.',
      moat: 'Trust in an unbranded category — rare and durable.',
      management: 'Tata governance.',
      industryOutlook: 'Formalisation tailwind intact.',
      financialSnapshot: 'Revenue growth ~18% | EBIT margin ~11%',
      keyRatios: 'P/E 68x · ROE 32%',
      exitStrategy: 'N/A — entry trigger below ₹2,900 (≈55x).',
      monitoringChecklist: 'Quarterly: studded mix, SSSG, gold price.',
      lessons: 'Watchlist discipline is a position. Not owning a great business at a bad price is an active decision, and it belongs in the record.',
      attachments: [],
    },
  },
]

export const LAB_JOURNAL = [
  { id: 'j-1', date: '2024-02-05', type: 'Sell', title: 'Exited Paytm at -28%', holdingId: 'h-paytm', body: 'RBI barred Paytm Payments Bank from accepting deposits. The thesis depended on a licence I did not control and could not monitor. Sold the full position the same session rather than average down. The loss is the tuition; the lesson is the pre-mortem.', tags: ['Mistake', 'Risk'], attachments: [] },
  { id: 'j-2', date: '2024-01-18', type: 'Reflection', title: 'On position sizing and unobservable risk', body: 'Reviewed every position for binary, unobservable dependencies — regulatory, key-man, single-customer. Two positions flagged. Added a rule: binary + unobservable ⇒ size assuming it can go to zero, or skip.', tags: ['Process'], attachments: [] },
  { id: 'j-3', date: '2023-10-02', type: 'Buy', title: 'Initiated Paytm — 3% starter', holdingId: 'h-paytm', body: 'Starter position on distribution optionality. Sized at 3% because governance was already a known concern. In hindsight the concern should have been disqualifying, not discounting.', tags: ['Entry'], attachments: [] },
  { id: 'j-4', date: '2023-09-05', type: 'Buy', title: 'Added Embassy REIT — yield sleeve', holdingId: 'h-embassy', body: 'Entered at ~18% discount to NAV, 6.8% distribution yield. The WFH-impairment narrative is priced as permanent; Grade-A leasing data disagrees.', tags: ['Entry', 'Income'], attachments: [] },
  { id: 'j-5', date: '2023-06-20', type: 'Buy', title: 'Initiated Infosys at 19x forward', holdingId: 'h-infy', body: 'Discretionary-spend fear at peak, buyback announced, 19x vs 24x median. The AI-disruption debate is the whole thesis — monitoring pricing per FTE quarterly.', tags: ['Entry'], attachments: [] },
  { id: 'j-6', date: '2023-04-12', type: 'Buy', title: 'Core position — HDFC Bank', holdingId: 'h-hdfcbank', body: 'Post-merger de-rating to 2.4x P/ABV. Entered in one tranche — should have laddered. Conviction right, execution schedule wrong.', tags: ['Entry', 'Core'], attachments: [] },
  { id: 'j-7', date: '2023-04-01', type: 'Research Update', title: 'Portfolio construction — opening framework', body: 'Opening the book at ₹1 Cr. Structure: ~55% equity (concentrated, high conviction), 18% passive beta anchor, 12% sovereign duration, 10% gold ballast, balance cash. The passive sleeve exists to make stock-selection alpha measurable rather than assumed.', tags: ['Construction'], attachments: [] },
]

export const LAB_LETTERS = [
  { id: 'q-2024-q1', quarter: 'Q1 2024', date: '2024-04-05', title: 'On paying tuition', summary: 'The Paytm exit cost 28% on a 3% position — about 84bps of the book. The lesson is worth more than the loss.', marketView: 'Indian equities priced for perfection in mid-caps; large-cap financials remain the least crowded pocket of the market.', portfolioReview: 'Book +6.2% vs NIFTY 50 +4.8%. Attribution is almost entirely the gold sleeve and HDFC Bank re-rating; stock selection ex-those contributed roughly nothing.', lessons: 'Binary regulatory risk cannot be diversified away at the position level — it must be refused at the underwriting level.', pdfUrl: '' },
  { id: 'q-2023-q4', quarter: 'Q4 2023', date: '2024-01-08', title: 'Concentration without conviction is just risk', summary: 'Reviewed every position against its original thesis. Two failed the test and were flagged.', marketView: 'Rate cycle appears to have peaked; extended duration in the sovereign sleeve accordingly.', portfolioReview: 'Book +9.1% vs NIFTY 50 +10.7% — underperformed. The cash drag and gold sleeve cost roughly 180bps in a strong up-quarter. That is the price of the insurance, and it was the right price.', lessons: 'Underperforming in an up-quarter is the expected cost of a ballast sleeve. Judging it quarterly is how good structure gets abandoned at the worst moment.', pdfUrl: '' },
]

export const LAB_RESEARCH_NOTES = [
  { id: 'rn-1', title: 'Reverse-DCF: what HDFC Bank\'s price actually implies', category: 'Valuation', date: '2024-03-12', summary: 'Working backwards from price to implied assumptions is more honest than forecasting forward. At ₹1,620 the market implied ~11% terminal loan growth — below the last decade\'s actual.', body: '', tags: ['DCF', 'Financials'], fileUrl: '' },
  { id: 'rn-2', title: 'Why the gold sleeve is a variance decision, not a return decision', category: 'Macro', date: '2024-01-22', summary: 'Gold has no cash flows, so it cannot be valued — only allocated. The correct question is what it does to portfolio variance in equity drawdowns.', body: '', tags: ['Allocation', 'Risk'], fileUrl: '' },
  { id: 'rn-3', title: 'Grade-A office: reading the leasing data against the narrative', category: 'Industry', date: '2023-11-30', summary: 'The WFH narrative and the Indian Grade-A leasing data have been diverging for six quarters. GCC expansion is the demand engine.', body: '', tags: ['REIT', 'Real Estate'], fileUrl: '' },
]

export const LAB_SEED = {
  settings: LAB_SETTINGS,
  holdings: LAB_HOLDINGS,
  journal: LAB_JOURNAL,
  letters: LAB_LETTERS,
  notes: LAB_RESEARCH_NOTES,
}
